// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qukzclnrxscrrhindgsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1a3pjbG5yeHNjcnJoaW5kZ3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3OTQwODEsImV4cCI6MjA4NjM3MDA4MX0.uQ4OiT-oHeLTzeFkTRDMMGiYCi0zakydJjAhszo-_o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});